twilio/twilio-verify-android

verify/build.gradle.kts
verify/src/main/java/com/twilio/verify/TwilioVerify.kt
verify/src/main/java/com/twilio/verify/logger/DefaultLoggerService.kt
verify/src/main/java/com/twilio/verify/logger/LogLevel.kt
verify/src/main/java/com/twilio/verify/logger/LogService.kt
verify/src/main/java/com/twilio/verify/logger/LogWrapper.kt
verify/src/main/java/com/twilio/verify/logger/Logger.kt
verify/src/main/java/com/twilio/verify/logger/LoggerService.kt
verify/src/test/java/com/twilio/verify/TwilioVerifyTest.kt
verify/src/test/java/com/twilio/verify/logger/DefaultLoggerServiceTest.kt
verify/src/test/java/com/twilio/verify/logger/LogWrapperTest.kt

- ACCSEC-18943
- Add LogWrapper and DefaultLoggerService

[ACCSEC-18943] Logging default service

---

sample/src/main/java/com/twilio/verify/sample/model/AccessTokenResponse.kt
sample/src/main/java/com/twilio/verify/sample/networking/SampleBackendAPIClient.kt
sample/src/main/java/com/twilio/verify/sample/view/Extensions.kt

- ACCSEC-19182
- Add annotation for proguard configuration in sample app.
- Show challenge details date in a new line
- SDK can be obfuscated, it won't need a proguard configuration

[ACCSEC-19182] Proguard configuration

---

.circleci/config.yml
Gemfile.lock
build.gradle.kts
buildSrc/src/main/kotlin/Config.kt
buildSrc/src/main/kotlin/Modules.kt
fastlane/Fastfile
fastlane/Pluginfile
sample/build.gradle.kts
sample/version
security/build.gradle.kts
security/gradle.properties
security/version
verify/build.gradle.kts
verify/gradle.properties

- ACCSEC-18827
- Sample app internal distribution for testing for all environments (dev, stg, prod)
- Prod build will only be generated when a new releases is triggered in main branch
- Dev and stage builds will be generated in feature, release, hotfix, dev branches
- https://console.firebase.google.com/u/0/project/twilioverify-sampleapp/appdistribution/app/android:com.twilio.verify.sample/releases
- https://app.circleci.com/pipelines/github/twilio/twilio-verify-android/1039/workflows/0564b1dc-9384-4d6b-b96e-d4b9021c5680/jobs/3730

[ACCSEC-18827] Sample app internal distribution

---

README.md
verify/src/androidTest/java/com/twilio/verify/BaseFactorTest.kt
verify/src/androidTest/java/com/twilio/verify/ClearLocalDataTests.kt
verify/src/main/java/com/twilio/verify/TwilioVerify.kt
verify/src/main/java/com/twilio/verify/data/Storage.kt
verify/src/main/java/com/twilio/verify/data/StorageProvider.kt
verify/src/main/java/com/twilio/verify/domain/TwilioVerifyManager.kt
verify/src/main/java/com/twilio/verify/domain/factor/FactorFacade.kt
verify/src/main/java/com/twilio/verify/domain/factor/FactorProvider.kt
verify/src/main/java/com/twilio/verify/domain/factor/FactorRepository.kt
verify/src/main/java/com/twilio/verify/domain/factor/PushFactory.kt
verify/src/test/java/com/twilio/verify/TwilioVerifyTest.kt
verify/src/test/java/com/twilio/verify/data/StorageTest.kt
verify/src/test/java/com/twilio/verify/domain/TwilioVerifyManagerTest.kt
verify/src/test/java/com/twilio/verify/domain/factor/FactorFacadeTest.kt
verify/src/test/java/com/twilio/verify/domain/factor/FactorRepositoryTest.kt
verify/src/test/java/com/twilio/verify/domain/factor/PushFactoryTest.kt

- ACCSEC-19360
- Add a method to clear local data in TwilioVerify interface
- Delete all factors in PushFactory
- Clear storage when an error occurred in PushFactory
- feat: Provide method in TwilioVerify to clear local data [ACCSEC-19360]

[ACCSEC-19360] Clear local storage method

---

verify/src/main/java/com/twilio/verify/logger/DefaultLoggerService.kt
verify/src/test/java/com/twilio/verify/logger/DefaultLoggerServiceTest.kt

[ACCSEC-19415] Update logs tag

---

README.md

- ACCSEC-20762
- Add additional step to download dependency from Maven Central

Update README installation steps to add library from Maven Central

---

fastlane/Fastfile
security/build.gradle.kts
verify/build.gradle.kts

- Changed sdk names to `twilio-verify-android` and `twilio-security-android`

Maven PoM sdk name

---

security/src/androidTest/java/com/twilio/security/crypto/AESGCMNoPaddingCipherTests.kt
security/src/test/java/com/twilio/security/crypto/key/cipher/AESCipherTest.kt

- ACCSEC-21632
- Add unit and instrumented tests to AESCipher
- Add test to AESCipher

[ACCSEC-21632] Add test to AESCipher

---

security/src/test/java/com/twilio/security/crypto/AndroidKeyStoreTest.kt
security/src/test/java/com/twilio/security/crypto/mocks/keystore/KeyStoreMock.kt
security/src/test/java/com/twilio/security/crypto/mocks/keystore/KeyStoreMockInput.kt
security/src/test/java/com/twilio/security/storage/EncryptedPreferencesTest.kt

- ACCSEC-21631
- Add tests for new encrypt and decrypt methods in AndroidKeyStore. 
- Add test for EncryptedPreferences using commit

ACCSEC-21631 Unit tests for AndroidKeyStore

---

security/src/test/java/com/twilio/security/storage/key/BiometricSecretKeyTest.kt

- ACCSEC-21636
- Unit tests for BiometricSecretKey

ACCSEC-21636 Unit tests for BiometricSecretKey

---

sample/src/main/java/com/twilio/verify/sample/view/Extensions.kt
sample/src/main/java/com/twilio/verify/sample/view/challenges/list/ChallengesAdapter.kt
sample/src/main/java/com/twilio/verify/sample/view/challenges/list/FactorChallengesFragment.kt
sample/src/main/java/com/twilio/verify/sample/view/challenges/update/ChallengeFragment.kt
sample/src/main/java/com/twilio/verify/sample/view/factors/create/CreateFactorFragment.kt
sample/src/main/java/com/twilio/verify/sample/view/factors/list/FactorsAdapter.kt
sample/src/main/java/com/twilio/verify/sample/view/factors/list/FactorsFragment.kt
sample/src/main/res/layout/fragment_challenge.xml
sample/src/main/res/layout/fragment_create_factor.xml
sample/src/main/res/layout/fragment_factors.xml
sample/src/main/res/layout/view_challenge.xml
sample/src/main/res/layout/view_factor.xml
sample/src/main/res/values/strings.xml

- ACCSEC-21712
- Add identifiers for views. 
- Split views

ACCSEC-21712 Add identifiers for views

---

security/build.gradle.kts
security/src/main/java/com/twilio/security/crypto/AndroidKeyStore.kt
security/src/main/java/com/twilio/security/crypto/key/authentication/BiometricAuthenticator.kt
security/src/main/java/com/twilio/security/storage/AuthenticatedEncryptedStorage.kt
security/src/main/java/com/twilio/security/storage/key/BiometricSecretKey.kt
security/src/test/java/com/twilio/security/crypto/key/cipher/BiometricAuthenticatorTests.kt
security/src/test/java/com/twilio/security/storage/key/BiometricSecretKeyTest.kt

[ACCSEC-21635] Manage biometric authentication errors

---

security/src/main/java/com/twilio/security/storage/AuthenticatedEncryptedPreferences.kt
security/src/test/java/com/twilio/security/crypto/key/authentication/BiometricAuthenticatorTests.kt
security/src/test/java/com/twilio/security/storage/AuthenticatedEncryptedPreferencesTest.kt

- ACCSEC-21637
- Add authenticated encrypted preferences tests

ACCSEC-21637 Authenticated encrypted preferences tests

---

sample/build.gradle.kts

- Use release keystore for debug build variant to generate APKs from different environments

Use keystore for debug

---

fastlane/Fastfile

- Create tag after pushing new version

chore: Create tag after pushing new version (#182)

---

security/gradle.properties
security/src/androidTest/java/com/twilio/security/storage/AuthenticatedEncryptedPreferencesTests.kt
security/src/main/java/com/twilio/security/storage/AuthenticatedEncryptedPreferences.kt
security/src/main/java/com/twilio/security/storage/AuthenticatedEncryptedStorage.kt
security/src/test/java/com/twilio/security/storage/AuthenticatedEncryptedPreferencesTest.kt

- Add callback when there is a success authentication

Add success callback to biometrics put

---

security/gradle.properties
security/src/androidTest/java/com/twilio/security/storage/AuthenticatedEncryptedPreferencesTests.kt
security/src/main/java/com/twilio/security/storage/AuthenticatedEncryptedPreferences.kt
security/src/main/java/com/twilio/security/storage/AuthenticatedEncryptedStorage.kt
security/src/main/java/com/twilio/security/storage/key/BiometricSecretKey.kt
security/src/test/java/com/twilio/security/storage/AuthenticatedEncryptedPreferencesTest.kt

Key recreation

---

README.md
sample/src/main/java/com/twilio/verify/sample/model/AppModel.kt
sample/src/main/java/com/twilio/verify/sample/push/FirebasePushService.kt
sample/src/main/java/com/twilio/verify/sample/view/challenges/list/FactorChallengesFragment.kt
sample/src/main/java/com/twilio/verify/sample/viewmodel/ChallengesViewModel.kt
sample/src/main/java/com/twilio/verify/sample/viewmodel/FactorViewModel.kt
sample/src/main/res/layout/fragment_factor_challenges.xml
sample/src/main/res/values/strings.xml
verify/src/main/java/com/twilio/verify/api/ChallengeAPIClient.kt
verify/src/main/java/com/twilio/verify/domain/challenge/ChallengeFacade.kt
verify/src/main/java/com/twilio/verify/domain/challenge/ChallengeProvider.kt
verify/src/main/java/com/twilio/verify/domain/challenge/ChallengeRepository.kt
verify/src/main/java/com/twilio/verify/models/ChallengeListPayload.kt
verify/src/test/java/com/twilio/verify/TwilioVerifyTest.kt
verify/src/test/java/com/twilio/verify/api/ChallengeAPIClientTest.kt
verify/src/test/java/com/twilio/verify/domain/TwilioVerifyManagerTest.kt
verify/src/test/java/com/twilio/verify/domain/challenge/ChallengeFacadeTest.kt
verify/src/test/java/com/twilio/verify/domain/challenge/ChallengeRepositoryTest.kt

Version 0.4.0

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

- ACCSEC-21769
- Added CONTRIBUTING.md section and file to README
- Added CODE_OF_CONDUCT.md file
- Added License section to README
- docs: add contributing.md

[21769] Add contributing.md

---

sample/src/main/java/com/twilio/verify/sample/view/factors/create/CreateFactorFragment.kt
security/gradle.properties
security/src/androidTest/java/com/twilio/security/storage/EncryptedPreferencesTests.kt
security/src/main/java/com/twilio/security/crypto/AndroidKeyStore.kt
security/src/main/java/com/twilio/security/storage/EncryptedPreferences.kt
security/src/test/java/com/twilio/security/crypto/AndroidKeyStoreTest.kt
security/src/test/java/com/twilio/security/storage/EncryptedPreferencesTest.kt
verify/src/androidTest/java/com/twilio/verify/ChallengeTests.kt
verify/src/main/java/com/twilio/verify/domain/challenge/ChallengeFacade.kt
verify/src/main/java/com/twilio/verify/domain/challenge/PushChallengeProcessor.kt
verify/src/main/java/com/twilio/verify/domain/factor/FactorFacade.kt
verify/src/test/java/com/twilio/verify/domain/challenge/ChallengeFacadeTest.kt
verify/src/test/java/com/twilio/verify/domain/factor/FactorFacadeTest.kt

- Validate challenge status before trying to update it. 
- Add validations for empty factor sid or challenge sid. 
- Get decrypt information correctly when the provider is not valid.

Version 0.6.0

---

README.md
sample/src/main/java/com/twilio/verify/sample/view/factors/create/CreateFactorFragment.kt
verify/src/main/java/com/twilio/verify/api/BaseAPIClient.kt
verify/src/main/java/com/twilio/verify/api/FactorAPIClient.kt
verify/src/main/java/com/twilio/verify/networking/NetworkAdapter.kt
verify/src/main/java/com/twilio/verify/networking/NetworkProvider.kt
verify/src/test/java/com/twilio/verify/networking/NetworkExceptionTest.kt

- Improved network error to get Verify API error

Version 0.6.1

---

.circleci/config.yml
sample/src/main/java/com/twilio/verify/sample/AppApplication.kt
sample/src/main/java/com/twilio/verify/sample/view/Extensions.kt
sample/src/main/java/com/twilio/verify/sample/view/factors/create/CreateFactorFragment.kt
sample/src/main/res/values/strings.xml

- [#####]
- ISSUE-
- Show snackbars with duration indefinite. 
- Add a button to dismiss them
- Improve snackbars in sample app

Show snackbars with duration indefinite. Add a button to dismiss them

---

.circleci/config.yml
sample/src/main/java/com/twilio/verify/sample/view/Extensions.kt
sample/src/main/java/com/twilio/verify/sample/view/factors/create/CreateFactorFragment.kt
sample/src/main/res/values/strings.xml

- [00000]
- Change the duratin the snackbars are shown to indefinite.
- Add an action button for snackbars that show any error.
- Update project param in Circle CI with the new project name in Firebase
- Improve snackbars in sample app

[00000] Improve snackbars in sample app

---

.circleci/config.yml
Gemfile
Gemfile.lock
sample/src/main/java/com/twilio/verify/sample/view/Extensions.kt
sample/src/main/java/com/twilio/verify/sample/view/factors/create/CreateFactorFragment.kt
sample/src/main/res/values/strings.xml

- [00000]
- ISSUE-
- Change the duratin the snackbars are shown to indefinite.
- Add an action button for snackbars that show any error.
- Update project param in Circle CI with the new project name in Firebase
- Improve snackbars in sample app

Improve snackbars in sample app

---

.circleci/config.yml
.github/CODEOWNERS
ftl/security-ftl-config.yaml
ftl/verify-ftl-config.yaml

- Use contexts
- Add code owners file
- chore: CI update

Use context
